### ISSUE TITLE
Move Bitmatrix-Generation (Vec<Vec<bool>>) to Method on Pcb

### ISSUE THREAD

**Issue by oberien** [main--/rust-factorio-ic#3]
and use it in mylee

**Comment by main--** [comment]
Not ideal. I‘d rather hold the pcb in a better data structure and query that directly instead.

**Comment by oberien** [comment]
I already refactored out a PCB struct and wanted to slowly move all methods onto it, such that we can easily replace those methods with better implementations. For now this would allow better streamlining of the code for mylee and the lee-lib.

**Comment by main--** [comment]
mylee code doesn't use a bitmatrix representation though

**Comment by oberien** [comment]
I wanted to streamline the preparation code of the two implementations, for example the loop, which iterates until any order of wires returns a result.

**Comment by main--** [comment]
`leemaze_lib` is legacy code, this is now obsolete.
